trigger:
 - master

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - script: |
      docker build -t playwright_docker -f ./dockerfile .
      echo "image built"
    displayName: 'Build Docker Image'

  - script: |
      docker run --rm playwright_docker
      echo "container ran successfully"
    displayName: 'Run Playwright Tests in Docker'

  - task: PublishBuildArtifacts@1
    condition: failed()  # Run only if the tests fail
    inputs:
      pathToPublish: 'playwright-report'
      artifactName: 'Test Results'
