trigger:
 - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - script: |
      docker build -t playwright_docker -f ./dockerfile .
      echo "image built"
    displayName: 'Build Docker Image'

  - script: |
      echo "container start"
      docker run playwright_docker
      echo "container succeeded"
    displayName: 'Run Playwright Tests in Docker'
    
  - task: PublishBuildArtifacts@1
    condition: failed()  # Run only if the tests fail
    inputs:
      pathToPublish: 'playwright-report'
      artifactName: 'Test Results'
