trigger:
 - master

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Setup Node.js'

  - script: |
      npm ci
      npx playwright install --with-deps
      npx playwright test
    displayName: 'Install Dependencies and Run Playwright Tests'

  - task: PublishBuildArtifacts@1
    condition: failed()  # Run only if the tests fail
    inputs:
      pathToPublish: 'playwright-report'
      artifactName: 'Test Results'
