trigger:
 - master

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - script: |
      docker build -t playwright_docker -f ./dockerfile .
      echo "image built"
    displayName: 'Build Docker Image'

  - script: |
      echo "starting docker container"
      docker run --rm playwright_docker
      echo "container ran successfully"
    displayName: 'Run Playwright Tests in Docker'
