trigger:
 - master

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - script: |
      docker build -t playwright_docker -f ./dockerfile .
      echo "image built"
    displayName: 'Build Docker Image'

  - script: |
    echo "Starting Docker container..."
    docker run --rm playwright_docker npx playwright test --reporter=list
    echo "Docker run completed."
  displayName: 'Run Playwright Tests in Docker with Logs'
