export const REGISTER_SELECTORS = {
    SIGNUP_NAME: "input[data-qa='signup-name']",
    SIGNUP_EMAIL: "input[data-qa='signup-email']",
    SIGNUP_BUTTON: "button[data-qa='signup-button']",
    GENDER1: "#id_gender1",
    PASSWORD: "#password",
    DAYS: "#days",
    MONTHS: "#months",
    YEARS: "#years",
    NEWSLETTER: "#newsletter",
    SPECIAL_OFFERS: "#optin", 
    FIRST_NAME: "#first_name",
    LAST_NAME: "#last_name",
    COMPANY: "#company",
    ADDRESS1: "#address1",
    ADDRESS2: "#address2",
    COUNTRY: "#country",
    STATE: "#state",
    CITY: "#city",
    ZIPCODE: "#zipcode",
    MOBILE_NUMBER: "#mobile_number",
    CREATE_ACCOUNT_BUTTON: "button[data-qa='create-account']",
    CONTINUE_BUTTON: "a[data-qa='continue-button']",
}